# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/tdp_bram/tdp_bram.xci
# IP: The module: 'tdp_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/tdp_bram/tdp_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdp_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/FPGA/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/tdp_bram/tdp_bram.xci
# IP: The module: 'tdp_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/tdp_bram/tdp_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdp_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
