# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys.xci
# IP: The module: 'clk_wiz_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys.xci
# IP: The module: 'clk_wiz_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Lectures/RISCV/RISCV_FPGA_TrueDualPort_Example/RISCV_FPGA.srcs/sources_1/ip/clk_wiz_sys/clk_wiz_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
